# Generated by Django 3.0.3 on 2020-02-19 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(unique=True)),
                ('samples', models.IntegerField(default=0)),
                ('verified', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sentences',
            },
        ),
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amar_project.Sentences')),
            ],
            options={
                'db_table': 'recordings',
            },
        ),
    ]
